# Minimal YAML to run a nginx HTTP server
kernel:
  image: linuxkit/kernel:4.9.x
  cmdline: "console=tty0 console=ttyS0 console=ttyAMA0"
init:
  - linuxkit/init:b3b75c18d82fb32b978c7d837fc896dafffd3a63
  - linuxkit/runc:1b0741d07949c0acc444cd6a04ee7f833443579d
  - linuxkit/containerd:bfb61cc1d26c39cd4b2bc08f7a9963fefa0ef3bf
onboot:
  - name: sysctl
    image: linuxkit/sysctl:a9ad57ed738a31ea9380cd73236866c312b35489
  - name: dhcpcd
    image: linuxkit/dhcpcd:48831507404049660b960e4055f544917d90378e
    command: ["/sbin/dhcpcd", "--nobackground", "-f", "/dhcpcd.conf", "-1"]
services:
  - name: getty
    image: linuxkit/getty:7bf4b3efef2a65c97ffb4decc1010cd4a232932b
    env:
     - INSECURE=true
  - name: nginx
    image: nginx:stable-alpine
    capabilities:
     - CAP_NET_BIND_SERVICE
     - CAP_CHOWN
     - CAP_SETUID
     - CAP_SETGID
     - CAP_DAC_OVERRIDE
    net: host
trust:
  org:
    - linuxkit
    - library
